### ISSUE TITLE
Dead Link to Setup Document in Readme.md

### ISSUE THREAD

**Issue by KaynSD** [EcsRx/ecsrx#14]
- Link for setup document in readme.md links to a 404 Page (https://github.com/EcsRx/ecsrx/blob/master/docs/setup.md)
- Should probably link to (https://ecsrx.gitbook.io/project/getting-started/setup)

**Comment by grofit** [comment]
Which file is the setup linked from? as I looked in the root readme and its not in there

**Comment by KaynSD** [comment]
Directly from readme.md:
```
## Quick Start
It is advised to look at the [setup docs](https://github.com/EcsRx/ecsrx/blob/master/docs/setup.md)"
```

**Comment by grofit** [comment]
Sorry, found the bit you mean, corrected link.
