### ISSUE TITLE
Documentation: IObservableGroupManager no longer exists

### ISSUE THREAD

**Issue by erinloy** [EcsRx/ecsrx#21]
https://ecsrx.gitbook.io/project/the-framework/observable-groups

IObservableGroupManager apparently no longer exists in code, but is referenced in docs.

**Comment by grofit** [comment]
Hey not sure if I/You/Someone has updated this but this seems to be right currently, as there is an `IObservableGroup` but it could very well be at that point in time there wasnt. I will leave this open for now but if you do think its solved and detailed enough you can close it or let me know a bit more about what is needed.

**Comment by grofit** [comment]
I am closing this one as it seems invalid now, but feel free to re-open it if its still applicable.
