### ISSUE TITLE
Bug when implementing multiple IReactToDataSystem<T> 

### ISSUE THREAD

**Issue by Fijo** [EcsRx/ecsrx#35]
I just noticed a bug when using more than one IReactToDataSystem<T> on a single system.

Sadly to solve it properly it also requires changes to SystemsRx. So I went ahead and just [created a unit test to demonstrate it](https://github.com/Cosmic-Shores/ecsrx/commit/2fc7106becd94f5f02b35c90d2bd08ed0fdde37d) for now.

That test could be shorter but I wanted it to be a somewhat proper one.

**Comment by grofit** [comment]
Will take a look tomorrow chief, thanks again for raising all this stuff, it may also effect other systems as I never really accounted for multiple of the same interface but its quite possible in some scenarios.

**Comment by grofit** [comment]
I have added a PR for this fix if you are happy to cast an eye over it before I approve it, the test passes now.

https://github.com/EcsRx/ecsrx/pull/36

**Comment by grofit** [comment]
This has been merged in now
