### ISSUE TITLE
ComponentDatabase.GetComponents<T> throws cast exception on reference types

### ISSUE THREAD

**Issue by JayPavlina** [EcsRx/ecsrx#8]
It works for structs so it is due to not having strongly typed array for reference types

**Comment by grofit** [comment]
Thanks for raising, as you say it must be blowing up on the strongly typed references, as a work around you should be able to use `IComponent` as the generic and then cast each entry explicitly, but I want to move them to be strongly typed behind the scenes anyway, so will try to sort both things at once.

**Comment by grofit** [comment]
This has been fixed in the `Parallel` branch and test cases have been added for this scenario.

I will close this but feel free to re-open.
